eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://42.192.209.81:8761/eureka/'
localhost:
  test: true
spring:
  cloud:
    discovery:
      enable: true
    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: entrance
          uri: lb://entrance
          predicates:
            - Path= /entrance/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, mystical-service-Bar
        - id: stream
          uri: lb://stream
          predicates:
            - Path= /stream/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, mystical-service-Bar
        - id: auth
          uri: lb://auth
          predicates:
            - Path= /sso/**
            - Method=POST
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, mystical-service-Bar
  profiles: dev
